services:
  nginx-init:
    image: nginx:alpine
    container_name: vera-nginx-init
    ports:
      - "80:80"
    volumes:
      - ./nginx-init.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: vera-certbot-init
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot -d verabien.duckdns.org --email noreply@verabien.duckdns.org --agree-tos --no-eff-email
    depends_on:
      - nginx-init
